name: Build ZXMAK2
on: [ workflow_dispatch, push ]
jobs:
  Default:
    runs-on: windows-2019
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Prepare NuGet
        run: |
          nuget sources add -Name Default -Source https://api.nuget.org/v3/index.json
          nuget restore src\ZXVM.sln
      - name: Build project 
        run: |
          msbuild /t:Build /p:Configuration=Release src\ZXVM.sln
          msbuild /t:Build /p:Configuration=Release src\ZXMAK2.Hardware.Adlers\ZXMAK2.Hardware.Adlers.csproj
          msbuild /t:Build /p:Configuration=Release src\ZXMAK2.Hardware.WinForms\ZXMAK2.Hardware.WinForms.csproj
          msbuild /t:Build /p:Configuration=Release src\ZXMAK2.Host.WinForms\ZXMAK2.Host.WinForms.csproj
      - name: Zip ROMS
        shell: pwsh
        run: |
          Compress-Archive src\_binrelease\roms\* src\_binrelease\ROMS.pak
          Remove-Item -LiteralPath src\_binrelease\roms -Force -Recurse
      - name: Archive release
        uses: actions/upload-artifact@v4
        with:
          name: ZXMAK2
          path: src/_binrelease/*
  wiki:
    name: Publish to GitHub Wiki
    runs-on: ubuntu-latest
    needs: Default
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}
          path: ${{github.repository}}
      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: ${{github.repository}}.wiki
      - name: Push to wiki
        run: |
          set -e
          cd $GITHUB_WORKSPACE/${{github.repository}}.wiki
          cp -r $GITHUB_WORKSPACE/${{github.repository}}/ZXMAK2.zip .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "action: wiki sync" && git push